export const Actions = {
    BASIC_FULL_NAME: 'BASIC_FULL_NAME',
    BASIC_EMAIL: 'BASIC_EMAIL',
    BASIC_NICK_NAME: 'BASIC_NICK_NAME',
    BASIC_PHONE: 'BASIC_PHONE',
    BASIC_TERMS_VERIFY: 'BASIC_TERMS_VERIFY'
}
