export const Actions = {
    VALIDATE_FULL_NAME: 'VALIDATE_FULL_NAME',
    VALIDATE_EMAIL: 'VALIDATE_EMAIL',
    VALIDATE_BIRTHDAY: 'VALIDATE_BIRTHDAY',
    VALIDATE_TERMS_PRIVACY: 'VALIDATE_TERMS_PRIVACY'
}
