export const Constants = {
    CERTIFICATES_CERTIFICATES: 'CETTIFICATES_CERTIFICATES',
    CERTIFICATES_TEAM_NAME: 'CERTIFICATES_TEAM_NAME',
    CERTIFICATES_INSTITUTION: 'CERTIFICATES_INSTITUTION',
    CERTIFICATES_GRADUATION: 'CERTIFICATES_GRADUATION'
}